/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Endpoint */
        post: operations["select_endpoint_select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Instance Endpoint */
        post: operations["instance_endpoint_instance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Endpoint */
        get: operations["catalog_endpoint_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Detail Endpoint */
        get: operations["catalog_detail_endpoint_catalog__candidate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Engines Endpoint */
        get: operations["engines_endpoint_engines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Presets Endpoint */
        get: operations["presets_endpoint_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AggregationPolicy */
        AggregationPolicy: {
            /** Neutral */
            neutral: number;
            compose: components["schemas"]["Compose"];
        };
        /** AndNode */
        AndNode: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "AND";
            /** Children */
            children: (components["schemas"]["TaskNode"] | components["schemas"]["SeqNode"] | components["schemas"]["AndNode"] | components["schemas"]["XorNode"] | components["schemas"]["LoopNode"] | components["schemas"]["ElementNode"])[];
            /** Description */
            description?: string | null;
        };
        /** AttributeBoundConstraint */
        AttributeBoundConstraint: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ATTRIBUTE_BOUND";
            /**
             * Scope
             * @enum {string}
             */
            scope: "GLOBAL" | "LOCAL";
            /** Tasks */
            tasks?: string[] | null;
            /** Candidates */
            candidates?: string[] | null;
            /** Attribute Id */
            attribute_id: string;
            op: components["schemas"]["ConstraintOp"];
            /** Value */
            value: number | components["schemas"]["NumericRange"];
            /**
             * Hard
             * @default true
             */
            hard: boolean;
            /** Description */
            description?: string | null;
        };
        /** Candidate */
        Candidate: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** Provider Id */
            provider_id: string;
            /** Name */
            name: string;
            /** Features */
            features: {
                [key: string]: number;
            };
            /** Description */
            description?: string | null;
        };
        /** CatalogDetailResponseEnvelope */
        CatalogDetailResponseEnvelope: {
            /** Result */
            result: {
                [key: string]: unknown;
            };
            timings_ms: components["schemas"]["CatalogDetailTimingsResponse"];
        };
        /** CatalogDetailTimingsResponse */
        CatalogDetailTimingsResponse: {
            /** Catalog Ms */
            catalog_ms: number;
            /** Catalog Cache Hit */
            catalog_cache_hit: boolean | null;
            /** Catalog Fetched At */
            catalog_fetched_at: string | null;
            /** Calibration Ms */
            calibration_ms: number;
            /** Request Total Ms */
            request_total_ms: number;
        };
        /** CatalogResponseEnvelope */
        CatalogResponseEnvelope: {
            /** Result */
            result: {
                [key: string]: unknown;
            }[];
            timings_ms: components["schemas"]["CatalogTimingsResponse"];
        };
        /** CatalogTimingsResponse */
        CatalogTimingsResponse: {
            /** Catalog Ms */
            catalog_ms: number;
            /** Catalog Cache Hit */
            catalog_cache_hit: boolean | null;
            /** Catalog Fetched At */
            catalog_fetched_at: string | null;
            /** Request Total Ms */
            request_total_ms: number;
        };
        /** Compose */
        Compose: {
            seq?: components["schemas"]["ComposeFn"] | null;
            and?: components["schemas"]["ComposeFn"] | null;
            xor?: components["schemas"]["ComposeFn"] | null;
            loop?: components["schemas"]["ComposeFn"] | null;
        };
        /** ComposeFn */
        ComposeFn: {
            fn: components["schemas"]["ComposeFnName"];
        };
        /**
         * ComposeFnName
         * @enum {string}
         */
        ComposeFnName: "SUM" | "PRODUCT" | "MAX" | "MIN" | "SCALED_SUM" | "SCALED_PRODUCT" | "SCALED_MIN" | "SCALED_MAX" | "MEAN";
        /** ConstraintItem */
        ConstraintItem: {
            /** Feature */
            feature: string;
            op: components["schemas"]["ConstraintOp"];
            /** Value */
            value: number;
        };
        /**
         * ConstraintOp
         * @enum {string}
         */
        ConstraintOp: "<=" | ">=" | "==" | "<" | ">" | "IN_RANGE";
        /** DependencyConstraint */
        DependencyConstraint: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "DEPENDENCY";
            type: components["schemas"]["DependencyType"];
            /** Tasks */
            tasks: string[];
            /**
             * Hard
             * @default true
             */
            hard: boolean;
            /** Description */
            description?: string | null;
        };
        /**
         * DependencyType
         * @enum {string}
         */
        DependencyType: "SAME_PROVIDER" | "DIFFERENT_PROVIDER";
        /**
         * Direction
         * @enum {string}
         */
        Direction: "MAXIMIZE" | "MINIMIZE";
        /** ElementNode */
        ElementNode: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ELEMENT";
            /** Description */
            description?: string | null;
        };
        /** EnginesResponseEnvelope */
        EnginesResponseEnvelope: {
            /** Result */
            result: {
                [key: string]: unknown;
            }[];
            timings_ms: components["schemas"]["RequestTimingsResponse"];
        };
        /**
         * Feasibility
         * @enum {string}
         */
        Feasibility: "FEASIBLE" | "INFEASIBLE" | "UNKNOWN";
        /** Feature */
        Feature: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            direction: components["schemas"]["Direction"];
            /** Unit */
            unit: string;
            scale: components["schemas"]["Scale"];
            valid_range: components["schemas"]["NumericRange"];
            /** Description */
            description?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Instance
         * @description The BIM tuple I=(T,P,C,F,G,Λ,Δ,O) — 'Compact QoS-Aware Service Composition'.
         */
        Instance: {
            metadata: components["schemas"]["InstanceMetadata"];
            /** Providers */
            providers: components["schemas"]["ProviderRef"][];
            /** Tasks */
            tasks: components["schemas"]["TaskRef"][];
            /** Candidates */
            candidates: components["schemas"]["Candidate"][];
            /** Features */
            features: components["schemas"]["Feature"][];
            composition: components["schemas"]["StructuredTree"];
            /** Aggregation Policies */
            aggregation_policies: {
                [key: string]: components["schemas"]["AggregationPolicy"];
            };
            /** Constraints */
            constraints?: (components["schemas"]["AttributeBoundConstraint"] | components["schemas"]["DependencyConstraint"])[];
            /** Objective */
            objective: components["schemas"]["MonoObjective"] | components["schemas"]["MultiObjective"] | components["schemas"]["ManyObjective"];
        };
        /** InstanceMetadata */
        InstanceMetadata: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** InstanceRequest */
        InstanceRequest: {
            /** Circuit Qasm */
            circuit_qasm: string;
            /**
             * @default {
             *       "pareto": false
             *     }
             */
            preferences: components["schemas"]["PreferencesRequest"];
            /**
             * Shots
             * @default 1024
             */
            shots: number;
            /**
             * Live
             * @default true
             */
            live: boolean;
            /** Snapshot Path */
            snapshot_path?: string | null;
            /** Providers */
            providers?: string[] | null;
            /**
             * Force Refresh
             * @default true
             */
            force_refresh: boolean;
        };
        /** InstanceResponseEnvelope */
        InstanceResponseEnvelope: {
            result: components["schemas"]["Instance"];
            timings_ms: components["schemas"]["TimingsResponse"];
        };
        /**
         * InstanceTimings
         * @description Timings for build_instance() alone — no catalog fetch, since
         *     build_instance() is handed an already-fetched resource list.
         */
        InstanceTimings: {
            /** Transpile Ms */
            transpile_ms: number;
            /** Features Ms */
            features_ms: number;
            /** Build Instance Ms */
            build_instance_ms: number;
            /** Total Ms */
            total_ms: number;
            /** Per Resource */
            per_resource?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Infeasible Reasons */
            infeasible_reasons?: {
                [key: string]: string;
            };
        };
        /** LoopBounds */
        LoopBounds: {
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
        };
        /** LoopNode */
        LoopNode: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "LOOP";
            /** Body */
            body: components["schemas"]["TaskNode"] | components["schemas"]["SeqNode"] | components["schemas"]["AndNode"] | components["schemas"]["XorNode"] | components["schemas"]["LoopNode"] | components["schemas"]["ElementNode"];
            /** Expected Iterations */
            expected_iterations?: number | null;
            bounds?: components["schemas"]["LoopBounds"] | null;
            /** Description */
            description?: string | null;
        };
        /** ManyObjective */
        ManyObjective: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MANY";
            /** Targets */
            targets: string[];
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /**
             * Weights Sum To One
             * @default true
             */
            weights_sum_to_one: boolean;
        };
        /** MonoObjective */
        MonoObjective: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MONO";
            /** Targets */
            targets: string[];
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /**
             * Weights Sum To One
             * @default true
             */
            weights_sum_to_one: boolean;
        };
        /** MultiObjective */
        MultiObjective: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MULTI";
            /** Targets */
            targets: string[];
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /**
             * Weights Sum To One
             * @default true
             */
            weights_sum_to_one: boolean;
        };
        /** NumericRange */
        NumericRange: {
            /** Min */
            min: number;
            /** Max */
            max: number;
        };
        /** PreferencesRequest */
        PreferencesRequest: {
            /** Preset */
            preset?: string | null;
            /** Weights */
            weights?: {
                [key: string]: number;
            } | null;
            /** Constraints */
            constraints?: components["schemas"]["ConstraintItem"][] | null;
            /** Require Provider */
            require_provider?: string | null;
            /**
             * Pareto
             * @default false
             */
            pareto: boolean;
        };
        /** PresetsResponseEnvelope */
        PresetsResponseEnvelope: {
            /** Result */
            result: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            timings_ms: components["schemas"]["RequestTimingsResponse"];
        };
        /** Provenance */
        Provenance: {
            /** Engine Id */
            engine_id: string;
            /** Execution Time Ms */
            execution_time_ms?: number | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** ProviderRef */
        ProviderRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** RequestTimingsResponse */
        RequestTimingsResponse: {
            /** Request Total Ms */
            request_total_ms: number;
        };
        /**
         * Scale
         * @enum {string}
         */
        Scale: "RATIO" | "INTERVAL" | "ORDINAL";
        /** SelectRequest */
        SelectRequest: {
            /** Circuit Qasm */
            circuit_qasm: string;
            /**
             * @default {
             *       "pareto": false
             *     }
             */
            preferences: components["schemas"]["PreferencesRequest"];
            /**
             * Shots
             * @default 1024
             */
            shots: number;
            /**
             * Live
             * @default true
             */
            live: boolean;
            /** Snapshot Path */
            snapshot_path?: string | null;
            /** Providers */
            providers?: string[] | null;
            /** Engine Id */
            engine_id?: string | null;
            /**
             * Force Refresh
             * @default true
             */
            force_refresh: boolean;
        };
        /** SelectResponseEnvelope */
        SelectResponseEnvelope: {
            result: components["schemas"]["SolveResponse"];
            timings_ms: components["schemas"]["TimingsResponse"];
        };
        /** SeqNode */
        SeqNode: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "SEQ";
            /** Children */
            children: (components["schemas"]["TaskNode"] | components["schemas"]["SeqNode"] | components["schemas"]["AndNode"] | components["schemas"]["XorNode"] | components["schemas"]["LoopNode"] | components["schemas"]["ElementNode"])[];
            /** Description */
            description?: string | null;
        };
        /** Solution */
        Solution: {
            /** Objective Value */
            objective_value?: number | null;
            /** Binding */
            binding: {
                [key: string]: string;
            };
            /** Aggregated Features */
            aggregated_features?: {
                [key: string]: number;
            };
            /** Violations */
            violations?: components["schemas"]["ValidationViolation"][];
        };
        /** SolveResponse */
        SolveResponse: {
            /** @default UNKNOWN */
            feasibility: components["schemas"]["Feasibility"];
            /** Solutions */
            solutions: components["schemas"]["Solution"][];
            provenance: components["schemas"]["Provenance"];
            /** Diagnostics */
            diagnostics?: {
                [key: string]: unknown;
            } | null;
        };
        /** StructuredTree */
        StructuredTree: {
            /**
             * Type
             * @default STRUCTURED
             * @constant
             */
            type: "STRUCTURED";
            /** Root */
            root: components["schemas"]["TaskNode"] | components["schemas"]["SeqNode"] | components["schemas"]["AndNode"] | components["schemas"]["XorNode"] | components["schemas"]["LoopNode"] | components["schemas"]["ElementNode"];
        };
        /** TaskNode */
        TaskNode: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "TASK";
            /** Task Id */
            task_id: string;
            /** Description */
            description?: string | null;
        };
        /** TaskRef */
        TaskRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * TimingsResponse
         * @description PhaseTimings plus the one thing only the API layer knows: how long
         *     the whole HTTP request took. A real extension, not a mirror — every
         *     other field is inherited from PhaseTimings itself, so a new field there
         *     shows up here for free instead of needing a hand-kept copy.
         */
        TimingsResponse: {
            /** Catalog Ms */
            catalog_ms: number;
            /** Catalog Cache Hit */
            catalog_cache_hit: boolean | null;
            /** Catalog Fetched At */
            catalog_fetched_at: string | null;
            instance: components["schemas"]["InstanceTimings"];
            /** Total Ms */
            total_ms: number;
            /** Request Total Ms */
            request_total_ms: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationViolation */
        ValidationViolation: {
            /** Constraint Id */
            constraint_id?: string | null;
            /** Message */
            message: string;
            /** Path */
            path?: string | null;
            /** Code */
            code: string;
            /** Stage */
            stage?: string | null;
            /** Penalty */
            penalty?: number | null;
            /** Description */
            description?: string | null;
        };
        /** XorBranch */
        XorBranch: {
            /** P */
            p: number;
            /** Child */
            child: components["schemas"]["TaskNode"] | components["schemas"]["SeqNode"] | components["schemas"]["AndNode"] | components["schemas"]["XorNode"] | components["schemas"]["LoopNode"] | components["schemas"]["ElementNode"];
        };
        /** XorNode */
        XorNode: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "XOR";
            /** Branches */
            branches: components["schemas"]["XorBranch"][];
            /** Description */
            description?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    select_endpoint_select_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelectResponseEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    instance_endpoint_instance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponseEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_endpoint_catalog_get: {
        parameters: {
            query?: {
                live?: boolean;
                provider?: string[] | null;
                /** @description Skip the 90s catalog cache and fetch live, even if it's still warm. */
                force_refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponseEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_detail_endpoint_catalog__candidate_id__get: {
        parameters: {
            query?: {
                live?: boolean;
                /** @description Skip the 90s catalog cache and fetch live, even if it's still warm. */
                force_refresh?: boolean;
            };
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogDetailResponseEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    engines_endpoint_engines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnginesResponseEnvelope"];
                };
            };
        };
    };
    presets_endpoint_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetsResponseEnvelope"];
                };
            };
        };
    };
}
