"""initial binding_log and catalog_telemetry tables

Revision ID: 6d7aaf77392c
Revises: 
Create Date: 2026-07-07 14:29:28.978160

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6d7aaf77392c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binding_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feasibility', sa.String(), nullable=False),
    sa.Column('engine_id', sa.String(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('solutions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binding_log_created_at'), 'binding_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_binding_log_source'), 'binding_log', ['source'], unique=False)
    op.create_table('catalog_telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sampled_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('num_qubits', sa.Integer(), nullable=False),
    sa.Column('queue_length', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('operational', sa.Boolean(), nullable=False),
    sa.Column('last_calibrated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_telemetry_provider_id'), 'catalog_telemetry', ['provider_id'], unique=False)
    op.create_index(op.f('ix_catalog_telemetry_resource_id'), 'catalog_telemetry', ['resource_id'], unique=False)
    op.create_index(op.f('ix_catalog_telemetry_sampled_at'), 'catalog_telemetry', ['sampled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_telemetry_sampled_at'), table_name='catalog_telemetry')
    op.drop_index(op.f('ix_catalog_telemetry_resource_id'), table_name='catalog_telemetry')
    op.drop_index(op.f('ix_catalog_telemetry_provider_id'), table_name='catalog_telemetry')
    op.drop_table('catalog_telemetry')
    op.drop_index(op.f('ix_binding_log_source'), table_name='binding_log')
    op.drop_index(op.f('ix_binding_log_created_at'), table_name='binding_log')
    op.drop_table('binding_log')
    # ### end Alembic commands ###
